"""
Script to add MCP implementation cells to Concierge_Agent.ipynb
"""
import json

# Read the notebook
with open('Concierge_Agent.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Find the position after the imports (after cell with ADK imports)
# We'll add new cells after the cell that imports ADK components
insert_position = None
for idx, cell in enumerate(notebook['cells']):
    if cell['cell_type'] == 'code' and 'source' in cell:
        source_text = ''.join(cell['source'])
        if 'from google.adk.tools.mcp_tool.mcp_toolset import McpToolset' in source_text:
            insert_position = idx + 1
            break

if insert_position is None:
    print("Could not find import cell, adding after cell 3")
    insert_position = 4

# Create new cells for MCP implementation

# Cell 1: Markdown explaining MCP
mcp_markdown_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## MCP (Model Context Protocol) Implementation\\n",
        "\\n",
        "This section implements a proper MCP server for the concierge agent. MCP is a standardized protocol for exposing tools and resources that can be used by AI agents.\\n",
        "\\n",
        "**Benefits of MCP:**\\n",
        "- Standardized interface for tool calling\\n",
        "- Better interoperability between different AI systems\\n",
        "- Easier debugging and monitoring\\n",
        "- Can be used with multiple MCP clients\\n",
        "\\n",
        "We'll create an MCP server that exposes all 23 concierge tools."
    ]
}

# Cell 2: MCP Server Implementation
mcp_server_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# MCP Server Implementation\\n",
        "from mcp.server import Server\\n",
        "from mcp.types import Tool, TextContent\\n",
        "import mcp.server.stdio\\n",
        "\\n",
        "# Create MCP server instance\\n",
        "mcp_server = Server(\\\"concierge-agent\\\")\\n",
        "\\n",
        "# Register all planning tools\\n",
        "@mcp_server.call_tool()\\n",
        "async def call_tool(name: str, arguments: dict) -> list[TextContent]:\\n",
        "    \\\"\\\"\\\"Handle tool calls from MCP clients\\\"\\\"\\\"\\n",
        "    \\n",
        "    # Planning Tools\\n",
        "    if name == \\\"suggest_destinations\\\":\\n",
        "        result = suggest_destinations(\\n",
        "            arguments.get(\\\"budget\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"season\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"interests\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"create_itinerary\\\":\\n",
        "        result = create_itinerary(\\n",
        "            arguments.get(\\\"destination\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"days\\\", 1)\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"suggest_activities\\\":\\n",
        "        result = suggest_activities(\\n",
        "            arguments.get(\\\"city\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"interests\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    # Booking Tools\\n",
        "    elif name == \\\"search_flights\\\":\\n",
        "        result = search_flights(\\n",
        "            arguments.get(\\\"origin\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"destination\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"date\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"book_flight\\\":\\n",
        "        result = book_flight(\\n",
        "            arguments.get(\\\"flight_id\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"passenger_name\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"search_hotels\\\":\\n",
        "        result = search_hotels(\\n",
        "            arguments.get(\\\"city\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"check_in\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"book_hotel\\\":\\n",
        "        result = book_hotel(\\n",
        "            arguments.get(\\\"hotel_id\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"guest_name\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"book_ride\\\":\\n",
        "        result = book_ride(\\n",
        "            arguments.get(\\\"pickup\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"dropoff\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"book_activity\\\":\\n",
        "        result = book_activity(\\n",
        "            arguments.get(\\\"activity_name\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"date\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    # Utility Tools\\n",
        "    elif name == \\\"get_weather_forecast\\\":\\n",
        "        result = get_weather_forecast(arguments.get(\\\"city\\\", \\\"\\\"))\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"convert_currency\\\":\\n",
        "        result = convert_currency(\\n",
        "            arguments.get(\\\"amount\\\", 0.0),\\n",
        "            arguments.get(\\\"from_curr\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"to_curr\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"translate_text\\\":\\n",
        "        result = translate_text(\\n",
        "            arguments.get(\\\"text\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"target_lang\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"check_visa_requirements\\\":\\n",
        "        result = check_visa_requirements(\\n",
        "            arguments.get(\\\"citizenship\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"country\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"get_insurance_quote\\\":\\n",
        "        result = get_insurance_quote(\\n",
        "            arguments.get(\\\"destination\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"days\\\", 1)\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"get_emergency_contacts\\\":\\n",
        "        result = get_emergency_contacts(arguments.get(\\\"city\\\", \\\"\\\"))\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"get_flight_status\\\":\\n",
        "        result = get_flight_status(arguments.get(\\\"flight_number\\\", \\\"\\\"))\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"track_expense\\\":\\n",
        "        result = track_expense(\\n",
        "            arguments.get(\\\"item\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"amount\\\", 0.0)\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"get_budget_summary\\\":\\n",
        "        result = get_budget_summary()\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    # Social Tools\\n",
        "    elif name == \\\"update_user_preference\\\":\\n",
        "        result = update_user_preference(\\n",
        "            arguments.get(\\\"key\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"value\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"get_user_preferences\\\":\\n",
        "        result = get_user_preferences()\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"submit_feedback\\\":\\n",
        "        result = submit_feedback(\\n",
        "            arguments.get(\\\"rating\\\", 0),\\n",
        "            arguments.get(\\\"comment\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    elif name == \\\"share_to_social_media\\\":\\n",
        "        result = share_to_social_media(\\n",
        "            arguments.get(\\\"platform\\\", \\\"\\\"),\\n",
        "            arguments.get(\\\"content\\\", \\\"\\\")\\n",
        "        )\\n",
        "        return [TextContent(type=\\\"text\\\", text=result)]\\n",
        "    \\n",
        "    else:\\n",
        "        raise ValueError(f\\\"Unknown tool: {name}\\\")\\n",
        "\\n",
        "print(\\\"✅ MCP Server configured with all 23 tools.\\\")\\n"
    ]
}

# Cell 3: List MCP Tools
mcp_list_tools_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "@mcp_server.list_tools()\\n",
        "async def list_tools() -> list[Tool]:\\n",
        "    \\\"\\\"\\\"List all available MCP tools\\\"\\\"\\\"\\n",
        "    return [\\n",
        "        # Planning Tools\\n",
        "        Tool(\\n",
        "            name=\\\"suggest_destinations\\\",\\n",
        "            description=\\\"Suggests travel destinations based on budget, season, and interests\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"budget\\\": {\\\"type\\\": \\\"string\\\", \\\"description\\\": \\\"Budget level (low/medium/high)\\\"},\\n",
        "                    \\\"season\\\": {\\\"type\\\": \\\"string\\\", \\\"description\\\": \\\"Travel season\\\"},\\n",
        "                    \\\"interests\\\": {\\\"type\\\": \\\"string\\\", \\\"description\\\": \\\"User interests\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"budget\\\", \\\"season\\\", \\\"interests\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"create_itinerary\\\",\\n",
        "            description=\\\"Creates a day-by-day itinerary for a destination\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"destination\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"days\\\": {\\\"type\\\": \\\"integer\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"destination\\\", \\\"days\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"suggest_activities\\\",\\n",
        "            description=\\\"Suggests activities in a city based on interests\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"city\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"interests\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"city\\\", \\\"interests\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        # Booking Tools\\n",
        "        Tool(\\n",
        "            name=\\\"search_flights\\\",\\n",
        "            description=\\\"Searches for available flights\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"origin\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"destination\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"date\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"origin\\\", \\\"destination\\\", \\\"date\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"book_flight\\\",\\n",
        "            description=\\\"Books a flight\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"flight_id\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"passenger_name\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"flight_id\\\", \\\"passenger_name\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"search_hotels\\\",\\n",
        "            description=\\\"Searches for available hotels\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"city\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"check_in\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"city\\\", \\\"check_in\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"book_hotel\\\",\\n",
        "            description=\\\"Books a hotel\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"hotel_id\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"guest_name\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"hotel_id\\\", \\\"guest_name\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"book_ride\\\",\\n",
        "            description=\\\"Books a local transportation ride\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"pickup\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"dropoff\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"pickup\\\", \\\"dropoff\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"book_activity\\\",\\n",
        "            description=\\\"Books an activity or tour\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"activity_name\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"date\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"activity_name\\\", \\\"date\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        # Utility Tools\\n",
        "        Tool(\\n",
        "            name=\\\"get_weather_forecast\\\",\\n",
        "            description=\\\"Gets weather forecast for a city\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\\"city\\\": {\\\"type\\\": \\\"string\\\"}},\\n",
        "                \\\"required\\\": [\\\"city\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"convert_currency\\\",\\n",
        "            description=\\\"Converts currency from one to another\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"amount\\\": {\\\"type\\\": \\\"number\\\"},\\n",
        "                    \\\"from_curr\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"to_curr\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"amount\\\", \\\"from_curr\\\", \\\"to_curr\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"translate_text\\\",\\n",
        "            description=\\\"Translates text to target language\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"text\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"target_lang\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"text\\\", \\\"target_lang\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"check_visa_requirements\\\",\\n",
        "            description=\\\"Checks visa requirements for a country\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"citizenship\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"country\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"citizenship\\\", \\\"country\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"get_insurance_quote\\\",\\n",
        "            description=\\\"Gets travel insurance quote\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"destination\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"days\\\": {\\\"type\\\": \\\"integer\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"destination\\\", \\\"days\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"get_emergency_contacts\\\",\\n",
        "            description=\\\"Gets emergency contacts for a city\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\\"city\\\": {\\\"type\\\": \\\"string\\\"}},\\n",
        "                \\\"required\\\": [\\\"city\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"get_flight_status\\\",\\n",
        "            description=\\\"Checks flight status\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\\"flight_number\\\": {\\\"type\\\": \\\"string\\\"}},\\n",
        "                \\\"required\\\": [\\\"flight_number\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"track_expense\\\",\\n",
        "            description=\\\"Logs a travel expense\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"item\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"amount\\\": {\\\"type\\\": \\\"number\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"item\\\", \\\"amount\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"get_budget_summary\\\",\\n",
        "            description=\\\"Returns total expenses summary\\\",\\n",
        "            inputSchema={\\\"type\\\": \\\"object\\\", \\\"properties\\\": {}}\\n",
        "        ),\\n",
        "        # Social Tools\\n",
        "        Tool(\\n",
        "            name=\\\"update_user_preference\\\",\\n",
        "            description=\\\"Updates user preference\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"key\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"value\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"key\\\", \\\"value\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"get_user_preferences\\\",\\n",
        "            description=\\\"Gets all user preferences\\\",\\n",
        "            inputSchema={\\\"type\\\": \\\"object\\\", \\\"properties\\\": {}}\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"submit_feedback\\\",\\n",
        "            description=\\\"Submits user feedback\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"rating\\\": {\\\"type\\\": \\\"integer\\\"},\\n",
        "                    \\\"comment\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"rating\\\", \\\"comment\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "        Tool(\\n",
        "            name=\\\"share_to_social_media\\\",\\n",
        "            description=\\\"Shares content to social media\\\",\\n",
        "            inputSchema={\\n",
        "                \\\"type\\\": \\\"object\\\",\\n",
        "                \\\"properties\\\": {\\n",
        "                    \\\"platform\\\": {\\\"type\\\": \\\"string\\\"},\\n",
        "                    \\\"content\\\": {\\\"type\\\": \\\"string\\\"}\\n",
        "                },\\n",
        "                \\\"required\\\": [\\\"platform\\\", \\\"content\\\"]\\n",
        "            }\\n",
        "        ),\\n",
        "    ]\\n",
        "\\n",
        "print(\\\"✅ MCP Tool definitions registered.\\\")\\n"
    ]
}

# Cell 4: Markdown explaining MCP integration with ADK
mcp_adk_markdown = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Using MCP with ADK Agents\\n",
        "\\n",
        "Now we'll create a function to start the MCP server and integrate it with our ADK agents using `McpToolset`.\\n",
        "This allows our agents to use the standardized MCP protocol for tool calling."
    ]
}

# Insert the new cells
for i, cell in enumerate([mcp_markdown_cell, mcp_server_cell, mcp_list_tools_cell, mcp_adk_markdown]):
    notebook['cells'].insert(insert_position + i, cell)

# Write back the updated notebook
with open('Concierge_Agent.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=4, ensure_ascii=False)

print(f"✅ Successfully added {len([mcp_markdown_cell, mcp_server_cell, mcp_list_tools_cell, mcp_adk_markdown])} MCP cells to the notebook at position {insert_position}")
