import json
import os

notebook_path = r"d:\Learning\IITKML\Self_learning\Kaggle\Concierge_Agent\Concierge_Agent.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# --- 1. Update Imports & Add Classes (Cell 2 & 3 merged/updated) ---
new_imports_source = [
    "import os\n",
    "import json\n",
    "import asyncio\n",
    "import logging\n",
    "import time\n",
    "from dotenv import load_dotenv\n",
    "from google.adk.agents import Agent, ParallelAgent\n",
    "from google.adk.runners import InMemoryRunner\n",
    "from google.adk.tools import AgentTool, FunctionTool, google_search\n",
    "from google.genai import types\n",
    "\n",
    "# Load environment variables\n",
    "load_dotenv()\n",
    "\n",
    "if \"GOOGLE_API_KEY\" not in os.environ:\n",
    "    print(\"Warning: GOOGLE_API_KEY not found in environment. Please set it.\")\n",
    "else:\n",
    "    print(\"✅ Google API Key loaded.\")\n",
    "\n",
    "# --- Observability: Structured Logging ---\n",
    "class AgentLogger:\n",
    "    def __init__(self, name):\n",
    "        self.logger = logging.getLogger(name)\n",
    "        self.logger.setLevel(logging.INFO)\n",
    "        if not self.logger.handlers:\n",
    "            handler = logging.StreamHandler()\n",
    "            formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')\n",
    "            handler.setFormatter(formatter)\n",
    "            self.logger.addHandler(handler)\n",
    "\n",
    "    def log_step(self, step_name, details):\n",
    "        self.logger.info(f\"STEP: {step_name} | DETAILS: {details}\")\n",
    "\n",
    "    def log_error(self, error_msg):\n",
    "        self.logger.error(f\"ERROR: {error_msg}\")\n",
    "\n",
    "# --- Long-Term Memory: Memory Bank ---\n",
    "class MemoryBank:\n",
    "    def __init__(self, file_path=\"memory.json\"):\n",
    "        self.file_path = file_path\n",
    "        self.memory = self._load_memory()\n",
    "\n",
    "    def _load_memory(self):\n",
    "        if os.path.exists(self.file_path):\n",
    "            try:\n",
    "                with open(self.file_path, \"r\") as f:\n",
    "                    return json.load(f)\n",
    "            except:\n",
    "                return {\"user_prefs\": {}, \"trip_history\": []}\n",
    "        return {\"user_prefs\": {}, \"trip_history\": []}\n",
    "\n",
    "    def _save_memory(self):\n",
    "        with open(self.file_path, \"w\") as f:\n",
    "            json.dump(self.memory, f, indent=4)\n",
    "\n",
    "    def update_pref(self, key, value):\n",
    "        self.memory[\"user_prefs\"][key] = value\n",
    "        self._save_memory()\n",
    "        return f\"Preference updated: {key}={value}\"\n",
    "\n",
    "    def get_prefs(self):\n",
    "        return json.dumps(self.memory[\"user_prefs\"])\n",
    "\n",
    "# Initialize global memory and logger\n",
    "memory_bank = MemoryBank()\n",
    "logger = AgentLogger(\"ConciergeAgent\")\n",
    "print(\"✅ ADK components & Custom Classes initialized.\")\n"
]

# Update Cell 2 (Index 2)
nb["cells"][2]["source"] = new_imports_source
# Clear Cell 3 (Index 3)
nb["cells"][3]["source"] = []

# --- 2. Update Tools (Cell 5) ---
new_tools_source = [
    "# --- Planning Tools ---\n",
    "def suggest_destinations(budget: str, season: str, interests: str):\n",
    "    \"\"\"Suggests travel destinations based on user preferences.\"\"\"\n",
    "    logger.log_step(\"suggest_destinations\", f\"budget={budget}, season={season}\")\n",
    "    return json.dumps([\n",
    "        {\"city\": \"Kyoto\", \"country\": \"Japan\", \"reason\": \"Autumn foliage\", \"cost\": \"Medium\"},\n",
    "        {\"city\": \"Reykjavik\", \"country\": \"Iceland\", \"reason\": \"Northern lights\", \"cost\": \"High\"},\n",
    "        {\"city\": \"Bali\", \"country\": \"Indonesia\", \"reason\": \"Beaches\", \"cost\": \"Low\"}\n",
    "    ])\n",
    "\n",
    "def create_itinerary(destination: str, days: int):\n",
    "    \"\"\"Creates a day-by-day itinerary.\"\"\"\n",
    "    logger.log_step(\"create_itinerary\", f\"dest={destination}, days={days}\")\n",
    "    return json.dumps({f\"Day {i}\": f\"Activity in {destination}\" for i in range(1, days + 1)})\n",
    "\n",
    "def suggest_activities(city: str, interests: str):\n",
    "    \"\"\"Suggests activities in a city.\"\"\"\n",
    "    return json.dumps([\"Museum Tour\", \"Hiking\", \"Food Tasting\"])\n",
    "\n",
    "# --- Booking Tools ---\n",
    "def search_flights(origin: str, destination: str, date: str):\n",
    "    \"\"\"Searches for flights.\"\"\"\n",
    "    return json.dumps([{\"airline\": \"AirFly\", \"price\": 500, \"id\": \"FL123\"}])\n",
    "\n",
    "def book_flight(flight_id: str, passenger_name: str):\n",
    "    \"\"\"Books a flight.\"\"\"\n",
    "    logger.log_step(\"book_flight\", f\"id={flight_id}\")\n",
    "    return json.dumps({\"status\": \"confirmed\", \"ref\": \"BK-FL-001\"})\n",
    "\n",
    "def search_hotels(city: str, check_in: str):\n",
    "    \"\"\"Searches for hotels.\"\"\"\n",
    "    return json.dumps([{\"name\": \"Grand Hotel\", \"price\": 200, \"id\": \"HTL1\"}])\n",
    "\n",
    "def book_hotel(hotel_id: str, guest_name: str):\n",
    "    \"\"\"Books a hotel.\"\"\"\n",
    "    logger.log_step(\"book_hotel\", f\"id={hotel_id}\")\n",
    "    return json.dumps({\"status\": \"confirmed\", \"ref\": \"BK-HTL-001\"})\n",
    "\n",
    "def book_ride(pickup: str, dropoff: str):\n",
    "    \"\"\"Books a local ride.\"\"\"\n",
    "    return json.dumps({\"driver\": \"John\", \"eta\": \"5 mins\"})\n",
    "\n",
    "def book_activity(activity_name: str, date: str):\n",
    "    \"\"\"Books an activity ticket.\"\"\"\n",
    "    return json.dumps({\"status\": \"confirmed\", \"ticket\": \"ACT-001\"})\n",
    "\n",
    "# --- Utility Tools ---\n",
    "def get_weather_forecast(city: str):\n",
    "    \"\"\"Gets weather forecast.\"\"\"\n",
    "    return \"Sunny, 25°C\"\n",
    "\n",
    "def convert_currency(amount: float, from_curr: str, to_curr: str):\n",
    "    \"\"\"Converts currency.\"\"\"\n",
    "    return f\"{amount * 1.1:.2f} {to_curr}\"\n",
    "\n",
    "def translate_text(text: str, target_lang: str):\n",
    "    \"\"\"Translates text.\"\"\"\n",
    "    return f\"[Translated to {target_lang}]: {text}\"\n",
    "\n",
    "def check_visa_requirements(citizenship: str, country: str):\n",
    "    \"\"\"Checks visa requirements.\"\"\"\n",
    "    return \"Visa-free for 90 days (Simulated)\"\n",
    "\n",
    "def get_insurance_quote(destination: str, days: int):\n",
    "    \"\"\"Gets travel insurance quote.\"\"\"\n",
    "    return \"$50 Standard Plan\"\n",
    "\n",
    "def get_emergency_contacts(city: str):\n",
    "    \"\"\"Gets emergency contacts.\"\"\"\n",
    "    return \"Police: 911, Embassy: +1-555-0199\"\n",
    "\n",
    "def get_flight_status(flight_number: str):\n",
    "    \"\"\"Checks flight status.\"\"\"\n",
    "    return \"On Time\"\n",
    "\n",
    "def track_expense(item: str, amount: float):\n",
    "    \"\"\"Logs an expense.\"\"\"\n",
    "    return \"Expense logged.\"\n",
    "\n",
    "def get_budget_summary():\n",
    "    \"\"\"Returns total expenses.\"\"\"\n",
    "    return \"Total: $150\"\n",
    "\n",
    "# --- Social Tools (Updated with MemoryBank) ---\n",
    "def update_user_preference(key: str, value: str):\n",
    "    \"\"\"Updates user preference.\"\"\"\n",
    "    return memory_bank.update_pref(key, value)\n",
    "\n",
    "def get_user_preferences():\n",
    "    \"\"\"Gets user preferences.\"\"\"\n",
    "    return memory_bank.get_prefs()\n",
    "\n",
    "def submit_feedback(rating: int, comment: str):\n",
    "    \"\"\"Submits feedback.\"\"\"\n",
    "    logger.log_step(\"submit_feedback\", f\"rating={rating}\")\n",
    "    return \"Feedback received.\"\n",
    "\n",
    "def share_to_social_media(platform: str, content: str):\n",
    "    \"\"\"Shares content to social media.\"\"\"\n",
    "    return f\"Shared to {platform}.\"\n"
]
nb["cells"][5]["source"] = new_tools_source

# --- 3. Update Sub-Agents (Cell 7) ---
new_agents_source = [
    "# Planning Agent\n",
    "planning_agent = Agent(\n",
    "    name=\"PlanningAgent\",\n",
    "    model=\"gemini-2.5-flash-lite\",\n",
    "    instruction=\"\"\"You are a Travel Planner. Use your tools to suggest destinations, create itineraries, and suggest activities.\n",
    "    IMPORTANT: After using a tool, you MUST provide a text summary of the results to the user. Do not just return the tool output.\n",
    "    Ensure your final response is a string.\"\"\",\n",
    "    tools=[FunctionTool(suggest_destinations), FunctionTool(create_itinerary), FunctionTool(suggest_activities)],\n",
    "    output_key=\"planning_output\"\n",
    ")\n",
    "\n",
    "# Booking Agent\n",
    "booking_agent = Agent(\n",
    "    name=\"BookingAgent\",\n",
    "    model=\"gemini-2.5-flash-lite\",\n",
    "    instruction=\"\"\"You are a Booking Specialist. Use your tools to search and book flights, hotels, rides, and activities.\n",
    "    IMPORTANT: After using a tool, you MUST provide a text confirmation or summary of the booking details to the user.\n",
    "    Ensure your final response is a string.\"\"\",\n",
    "    tools=[\n",
    "        FunctionTool(search_flights), FunctionTool(book_flight),\n",
    "        FunctionTool(search_hotels), FunctionTool(book_hotel),\n",
    "        FunctionTool(book_ride), FunctionTool(book_activity)\n",
    "    ],\n",
    "    output_key=\"booking_output\"\n",
    ")\n",
    "\n",
    "# Utility Agent\n",
    "utility_agent = Agent(\n",
    "    name=\"UtilityAgent\",\n",
    "    model=\"gemini-2.5-flash-lite\",\n",
    "    instruction=\"\"\"You are a Travel Assistant. Provide info on weather, currency, visa, insurance, emergency contacts, and flight status.\n",
    "    Ensure your final response is a string.\"\"\",\n",
    "    tools=[\n",
    "        FunctionTool(get_weather_forecast), FunctionTool(convert_currency),\n",
    "        FunctionTool(translate_text), FunctionTool(check_visa_requirements),\n",
    "        FunctionTool(get_insurance_quote), FunctionTool(get_emergency_contacts),\n",
    "        FunctionTool(get_flight_status), FunctionTool(track_expense),\n",
    "        FunctionTool(get_budget_summary)\n",
    "    ],\n",
    "    output_key=\"utility_output\"\n",
    ")\n",
    "\n",
    "# Search Agent\n",
    "search_agent = Agent(\n",
    "    name=\"SearchAgent\",\n",
    "    model=\"gemini-2.5-flash-lite\",\n",
    "    instruction=\"\"\"You are a Real-Time Information Specialist. Use `google_search` to find up-to-date information.\n",
    "    Always summarize the search results clearly for the user. Ensure your final response is a string.\"\"\",\n",
    "    tools=[google_search],\n",
    "    output_key=\"search_output\"\n",
    ")\n",
    "\n",
    "# Parallel Info Agent (Combines Utility and Search)\n",
    "# This agent runs Utility and Search agents in parallel to gather comprehensive info.\n",
    "info_agent = ParallelAgent(\n",
    "    name=\"InfoGatheringAgent\",\n",
    "    agents=[utility_agent, search_agent],\n",
    "    output_key=\"info_output\"\n",
    ")\n",
    "\n",
    "# Social Agent\n",
    "social_agent = Agent(\n",
    "    name=\"SocialAgent\",\n",
    "    model=\"gemini-2.5-flash-lite\",\n",
    "    instruction=\"\"\"You handle User Profile and Socials. Update preferences, collect feedback, and share updates.\n",
    "    Use the `get_user_preferences` tool to check for existing preferences.\n",
    "    IMPORTANT: After using a tool, you MUST provide a text confirmation of the action to the user.\n",
    "    Ensure your final response is a string.\"\"\",\n",
    "    tools=[\n",
    "        FunctionTool(update_user_preference), FunctionTool(get_user_preferences),\n",
    "        FunctionTool(submit_feedback), FunctionTool(share_to_social_media)\n",
    "    ],\n",
    "    output_key=\"social_output\"\n",
    ")\n",
    "\n",
    "print(\"✅ Sub-agents created. InfoGatheringAgent (Parallel) added.\")\n"
]
nb["cells"][7]["source"] = new_agents_source

# --- 4. Update Root Agent (Cell 9) ---
new_root_source = [
    "root_agent = Agent(\n",
    "    name=\"ConciergeCoordinator\",\n",
    "    model=\"gemini-2.5-flash-lite\",\n",
    "    instruction=\"\"\"You are the Head Concierge. Your goal is to assist the user with their travel needs by coordinating with specialized agents.\n",
    "    - For planning (destinations, itineraries), call `PlanningAgent`.\n",
    "    - For bookings (flights, hotels, rides), call `BookingAgent`.\n",
    "    - For general information (weather, currency, news, visa), call `InfoGatheringAgent` (this runs utility and search in parallel).\n",
    "    - For social/profile (preferences, feedback, sharing), call `SocialAgent`.\n",
    "    \n",
    "    Always answer the user politely. If a sub-agent returns information, summarize it for the user and ask if they need anything else.\n",
    "    Ensure you pass the user's query correctly to the sub-agents.\"\"\",\n",
    "    tools=[\n",
    "        AgentTool(planning_agent),\n",
    "        AgentTool(booking_agent),\n",
    "        AgentTool(info_agent), # Parallel execution wrapper\n",
    "        AgentTool(social_agent)\n",
    "    ]\n",
    ")\n",
    "\n",
    "print(\"✅ Root Coordinator created with Parallel Info Agent.\")\n"
]
nb["cells"][9]["source"] = new_root_source

# --- 5. Update Run Loop (Cell 11) ---
new_run_source = [
    "runner = InMemoryRunner(agent=root_agent)\n",
    "\n",
    "async def run_demo():\n",
    "    print(\"--- Starting Concierge Demo (Type 'exit' to quit) ---\")\n",
    "    \n",
    "    # Initial complex query\n",
    "    initial_query = \"\"\"\n",
    "    I want to plan a trip to Japan in Autumn. Budget is medium.\n",
    "    Once you suggest a destination, please check the weather there and find me a hotel.\n",
    "    Also, save my preference for 'Asian Food'.\n",
    "    \"\"\"\n",
    "    \n",
    "    current_query = initial_query\n",
    "    \n",
    "    while True:\n",
    "        print(f\"\\nUser > {current_query}\\n\")\n",
    "        logger.log_step(\"User Input\", current_query)\n",
    "        \n",
    "        try:\n",
    "            # Run the agent\n",
    "            await runner.run_debug(current_query)\n",
    "        except TypeError as e:\n",
    "            print(f\"TypeError encountered: {e}. Retrying with simplified prompt...\")\n",
    "            logger.log_error(f\"TypeError: {e}\")\n",
    "        except Exception as e:\n",
    "            print(f\"Error during execution: {e}\")\n",
    "            logger.log_error(f\"Exception: {e}\")\n",
    "            break\n",
    "            \n",
    "        # For automated testing in this script, we break after the first run\n",
    "        # In a real interactive session, we would take input\n",
    "        break\n",
    "        # user_input = input(\"\\nEnter your reply (or 'exit'): \")\n",
    "        # if user_input.lower() in ['exit', 'quit']:\n",
    "        #     break\n",
    "        # current_query = user_input\n",
    "\n",
    "    print(\"\\n--- Demo Completed ---\")\n",
    "\n",
    "await run_demo()"
]
nb["cells"][11]["source"] = new_run_source

# Save the updated notebook
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=4)

print("Notebook updated successfully.")
