"""Report data model and validation."""

from datetime import datetime, date
from typing import Optional, List
from enum import Enum

from pydantic import BaseModel, Field, validator


class ReportType(str, Enum):
    """Report type enum."""

    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    CUSTOM = "custom"


class Report(BaseModel):
    """Report model."""

    report_id: str = Field(..., description="Unique report identifier")
    report_type: ReportType = Field(..., description="Type of report")
    period_start: date = Field(..., description="Report period start date")
    period_end: date = Field(..., description="Report period end date")
    inventory_turnover: float = Field(..., ge=0, description="Inventory turnover ratio")
    stockout_rate: float = Field(..., ge=0, le=1, description="Stockout rate 0-1")
    supplier_performance_score: float = Field(..., ge=0, le=100, description="Supplier performance score 0-100")
    forecast_accuracy: float = Field(..., ge=0, le=100, description="Forecast accuracy percentage 0-100")
    cost_savings: float = Field(default=0.0, ge=0, description="Cost savings amount")
    recommendations: List[str] = Field(default_factory=list, description="List of recommendations")
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    generated_by: str = Field(..., description="Agent name that generated the report")

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {
                "report_id": "RPT-001",
                "report_type": "weekly",
                "period_start": "2024-01-01",
                "period_end": "2024-01-07",
                "inventory_turnover": 4.5,
                "stockout_rate": 0.02,
                "supplier_performance_score": 92.0,
                "forecast_accuracy": 88.5,
                "cost_savings": 5000.00,
                "recommendations": ["Increase safety stock for PROD-001", "Review supplier performance"],
                "generated_by": "Report Generation Agent",
            }
        }

    @validator("report_id")
    def validate_report_id(cls, v):
        """Validate report ID."""
        if not v or len(v.strip()) == 0:
            raise ValueError("Report ID cannot be empty")
        return v.strip()

    @validator("generated_by")
    def validate_generated_by(cls, v):
        """Validate generated_by field."""
        if not v or len(v.strip()) == 0:
            raise ValueError("Generated by cannot be empty")
        return v.strip()

    @validator("period_end")
    def validate_period_dates(cls, v, values):
        """Validate that period_end is after period_start."""
        if "period_start" in values:
            if v < values["period_start"]:
                raise ValueError("Period end date must be after period start date")
        return v


class ReportValidator:
    """Validator for Report model."""

    @staticmethod
    def validate(data: dict) -> Report:
        """Validate and create a Report instance."""
        return Report(**data)

    @staticmethod
    def validate_batch(data_list: list) -> list:
        """Validate and create multiple Report instances."""
        return [Report(**data) for data in data_list]
